### ISSUE TITLE
USPTO Trademark Search API

### ISSUE THREAD

**Issue by kinlane** [api-evangelist/inbox#749]
```
aid: rapidapi.com:uspto-trademark
name: USPTO Trademark Search API
url: https://pastebin.com/f1dYLnve
type: Collection
description: >
  Instant trademark search. Check if a trademark keyword is available, or search
  trademarks, or owner information from United States Patent and Trademark
  Office. Updated Daily.


  The USPTO Trademark API helps you obtain trademark & service mark data in an
  efficient and comprehensive manner. Easily search for active marks & retrieve
  data pertaining to specific marks, such as the mark's name, serial and
  registration numbers, its status, owner information, and much more. Conduct
  keyword searches, scan a wide range of services, check mark availability,
  identify expiring trademarks, perform serial number, owner, and classification
  searches, and more.


  Key Features:

  - Keyword Search (generic and full text)

  - Trademark Availability Check

  - Expiring Trademarks by Date

  - Trademarks by Registration Date

  - Serial Number Search (detailed info)

  - Owner Search

  - Batch Processing for efficient data retrieval (up to 25,000 results for
  batch calls)

  - Pagination Support for large result sets

  - Database Status (freshness, latest updates, updated daily)

  - Classification code lookup

  - Filing and expiration date search

  - Status search for active and inactive trademarks.


  Use Cases:

  Businesses can scan millions of trademarks to ensure the availability of their
  desired mark. Software agencies can leverage the API to verify marks and
  conduct investigations. Researchers can analyze trademark data for trends and
  patterns. Individuals can check the availability of a mark before using it in
  their business or brand. Attorneys can quickly search and retrieve trademark
  information for their clients.


  Benefits:

  Easy to use and integrate, powerful search capabilities with flexible filters,
  access to a comprehensive and up-to-date database of trademarks, efficient
  batch processing, pagination support for easy navigation of large result sets,
  and regular database updates for the most current information.
image: >-
  https://rapidapi.com/hub/_next/image?url=https%3A%2F%2Frapidapi-prod-apis.s3.amazonaws.com%2F9440240c-7bf2-4af0-8232-375b0bb7327f_medium&w=1920&q=75
tags:
  - Trademark
  - USPTO
  - Legal
  - Search
  - Intellectual Property
  - Government Data
  - Business
  - Brand
  - Data
created: 2025-5-28
modified: 2025-5-28
specificationVersion: '0.19'
position: Provider
access: Public
apis:
  - aid: rapidapi.com:uspto-trademark:api
    name: USPTO Trademark Search API Endpoints
    description: >
      The core API for accessing USPTO trademark data, offering various search
      and retrieval functionalities including keyword search, availability
      check, serial number lookups, owner searches, and database status
      information. It supports batch processing and pagination.
    image: >-
      https://rapidapi.com/hub/_next/image?url=https%3A%2F%2Frapidapi-prod-apis.s3.amazonaws.com%2F9440240c-7bf2-4af0-8232-375b0bb7327f_medium&w=1920&q=75
    humanURL: https://rapidapi.com/pentium10/api/uspto-trademark
    baseURL: https://uspto-trademark.p.rapidapi.com
    tags:
      - Trademark Search
      - USPTO Data
      - Brand Protection
      - Legal Research
      - Data Retrieval
    properties:
      - type: Documentation
        url: https://rapidapi.com/pentium10/api/uspto-trademark
      - type: FAQ
        url: https://rapidapi.com/pentium10/api/uspto-trademark/tutorials/faq-
      - type: Documentation
        url: >-
          https://www.postman.com/pentium10/uspto-trademark-api/collection/2ezvmws/uspto-trademark-search-api
      - type: Pricing
        url: https://rapidapi.com/pentium10/api/uspto-trademark/pricing
      - type: Blog
        url: https://medium.com/p/71274363605b
        description: USPTO Trademark API — Search trademark & owner database — part 1
      - type: Blog
        url: https://medium.com/p/19efc7e1cc6
        description: >-
          Implementing trademark availability and search using USPTO Trademark
          API — part 2
      - type: StatusPage
        url: https://rapidapi.com/pentium10/api/uspto-trademark#endpoints
        description: >-
          Database freshness and update information available via
          /v1/databaseStatus endpoint.
      - type: TermsOfService
        url: https://rapidapi.com/terms/
    contact:
      - FN: MartonKodok
        email: android482-one@yahoo.com
        X-twitter: martonkodok
common:
  - type: Signup
    url: https://rapidapi.com/pentium10/api/uspto-trademark/
  - type: Login
    url: https://rapidapi.com/developer/dashboard
  - type: Documentation
    url: https://rapidapi.com/pentium10/api/uspto-trademark
  - type: Pricing
    url: https://rapidapi.com/pentium10/api/uspto-trademark/pricing
  - type: FAQ
    url: https://rapidapi.com/pentium10/api/uspto-trademark/tutorials/faq-
  - type: Documentation
    url: >-
      https://www.postman.com/pentium10/uspto-trademark-api/collection/2ezvmws/uspto-trademark-search-api
  - type: Blog
    url: https://medium.com/p/71274363605b
  - type: Blog
    url: https://medium.com/p/19efc7e1cc6
  - type: TermsOfService
    url: https://rapidapi.com/terms/
  - type: Twitter
    url: https://twitter.com/martonkodok
maintainers:
  - FN: MartonKodok
    email: android482-one@yahoo.com
    X-twitter: martonkodok
```
